[default]
SQLALCHEMY_DATABASE_URI = "postgresql://pedropina:15975378pP!@evenpi.postgres.database.azure.com/postgres?sslmode=require"
SECRET_KEY = "s321321321qsda2131!!SDASDe"
JWT_SECRET_KEY = "7E451C1EB42EEA6DBC1A783AF5E1E"
JWT_ACCESS_TOKEN_EXPIRES = 9999
JWT_REFRESH_TOKEN_EXPIRES  = 420
MAIL_SERVER = "smtp.office365.com"
MAIL_USERNAME = "simple.api.pp@outlook.com"
MAIL_PORT = "587"
MAIL_USE_TLS = "true"
MAIL_USER_SSL = "false"
MAIL_PASSWORD = "5541025pP!"

[testing]
SQLALCHEMY_DATABASE_URI = "sqlite:///testdb.db"
SECRET_KEY = "s321321321qsda2131!!SDASDe"
JWT_SECRET_KEY = "7E451C1EB42EEA6DBC1A783AF5E1E"
JWT_ACCESS_TOKEN_EXPIRES = 9999
JWT_REFRESH_TOKEN_EXPIRES  = 420
MAIL_SERVER = "smtp.office365.com"
MAIL_USERNAME = "simple.api.pp@outlook.com"
MAIL_PORT = "587"
MAIL_USE_TLS = "true"
MAIL_USER_SSL = "false"
MAIL_PASSWORD = "5541025pP!"