"""empty message

Revision ID: 796513b69115
Revises: a1f1a40a605c
Create Date: 2023-05-28 18:50:55.399927

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '796513b69115'
down_revision = 'a1f1a40a605c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('atividades', schema=None) as batch_op:
        batch_op.add_column(sa.Column('carga_horaria', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('atividades', schema=None) as batch_op:
        batch_op.drop_column('carga_horaria')

    # ### end Alembic commands ###
