"""empty message

Revision ID: a1f1a40a605c
Revises: 
Create Date: 2023-05-28 15:44:13.677210

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1f1a40a605c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('participante_atividade', schema=None) as batch_op:
        batch_op.add_column(sa.Column('checkin', sa.Boolean(), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cpf', sa.String(length=11), nullable=True))
        batch_op.add_column(sa.Column('date_birth', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('date_birth')
        batch_op.drop_column('cpf')

    with op.batch_alter_table('participante_atividade', schema=None) as batch_op:
        batch_op.drop_column('checkin')

    # ### end Alembic commands ###
