"""empty message

Revision ID: b6308ed1e838
Revises: 
Create Date: 2023-05-30 15:58:23.466295

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6308ed1e838'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('atividades', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fk_evento_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_evento', 'evento', ['fk_evento_id'], ['id'])
        batch_op.drop_column('fk_evento')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('atividades', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fk_evento', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint('fk_evento', type_='foreignkey')
        batch_op.create_foreign_key(None, 'evento', ['fk_evento'], ['id'])
        batch_op.drop_column('fk_evento_id')

    # ### end Alembic commands ###
