"""empty message

Revision ID: c6e91edc7627
Revises: 
Create Date: 2023-05-28 20:43:59.412373

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6e91edc7627'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('atividades', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fk_evento', sa.Integer(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'evento', ['fk_evento'], ['id'])
        batch_op.drop_column('evento_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('atividades', schema=None) as batch_op:
        batch_op.add_column(sa.Column('evento_id', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'evento', ['evento_id'], ['id'])
        batch_op.drop_column('fk_evento')

    # ### end Alembic commands ###
